### ISSUE TITLE
Add ability to configure compiler options

### ISSUE THREAD

**Issue by veelenga** [veelenga/vicr#5]
For example:

``` yaml
# ~/.vicr/init.yaml

---
...
compiler:
  executable: crystal
  args_before: "run --release"
  args_after: "-- --theads 2"
...
```

Which should be translated as follows:

``` sh
$ crystal run --release {run_file} -- --threads 2
```
